theme: jekyll-theme-minimal
timezone: europe/london

title: "Barry's blog"
description: "Some thoughts on life and technology"
show_downloads: false
google_analytics: UA-3047863-7

paginate: 3
paginate_path: "/blog/:num/"

defaults:
 -
   scope:
     path: ""
     type: "posts"
   values:
     layout: "default"
     author: "Barry"
     category: "General"
